const translations = {
  en: {
    menu: "Menu",
    zgara: "Grill",
    pije_f: "Refreshing Drinks",
    pije_a: "Alcoholic Drinks",
    kafe: "Coffee",
    caj: "Tea",
    qebapa_5: "5 Kebabs",
    qebapa_10: "10 Kebabs",
    pleskavic: "Burger (served on plate)",
    ramstek: "Rump-Steak",
    veshk: "Kidney",
    file_pule: "Chicken Fillet",
    mushkni: "Lung",
    suxhuk: "Sausage",
    kombinim: "Combination",
    peja: "Beer Peja",
    shkupi: "Beer Shkupi",
    niksichko: "Beer Niksichko",
    raki: "Grape Brandy",
    lasko: "Beer Lasko",
    kamomil: "Chamomile",
    menta: "Mint",
    brusnica: "Cranberry",
    frutamali: "Forest Fruit",
    molle: "Apple Juice",
    pjeshk: "Peach Juice",
    dredhez: "Strawberry Juice",
    vishnje: "Cherry Juice",
    boronic: "Blueberry Juice",
    portokall: "Orange Juice",
    uj: "Water",
    uj_g: "Sparkling Water",
    makiato_m: "Large Macchiato",
    makiato_v: "Small macchiato",
  },
  sq: {
    menu: "Menu",
    zgara: "Zgara",
    pije_f: "Pije Freskuse",
    pije_a: "Pije Alkoolike",
    kafe: "Kafe",
    caj: "Çaj",
    qebapa_5: "5 Qebapa",
    qebapa_10: "10 Qebapa",
    pleskavic: "Pleskavic",
    ramstek: "Ramstek",
    veshk: "Veshk",
    file_pule: "File Pule",
    mushkni: "Mushkni",
    suxhuk: "Suxhuk",
    kombinim: "Kombinim",
    peja: "Birra Peja",
    shkupi: "Birra Shkupi",
    niksichko: "Birra Niksichko",
    raki: "Raki Rrushi",
    lasko: "Birra Lasko",
    kamomil: "Çaj Kamomil",
    menta: "Çaj Menta",
    brusnica: "Çaj Brusnica",
    frutamali: "Çaj Fruta Mali",
    molle: "Mollë",
    pjeshk: "Pjeshk",
    dredhez: "Dredhëz",
    vishnje: "Vishnje",
    boronic: "Boronic",
    portokall: "Portokall",
    uj: "Uje",
    uj_g: "Uje i gazuar",
    makiato_m: "Machiato e madhe",
    makiato_v: "Machiato e vogel",
  }, 
  de: {
    menu: "Menü",
    zgara: "Grill",
    pije_f: "Erfrischungsgetränke",
    pije_a: "Alkoholische Getränke",
    kafe: "Kaffee",
    caj: "Tee",
    qebapa_5: "5 Ćevapčići",
    qebapa_10: "10 Ćevapčići",
    pleskavic: "Pljeskavica",
    ramstek: "Rumpsteak",
    veshk: "Niere",
    file_pule: "Hähnchenfilet",
    mushkni: "Lunge",
    suxhuk: "Knoblauch-Wurst",
    kombinim: "Kombinationsteller",
    peja: "Bier Peja",
    shkupi: "Bier Shkupi",
    niksichko: "Bier Nikšićko",
    raki: "Rakija",
    lasko: "Bier Laško",
    kamomil: "Kamillentee",
    menta: "Pfefferminztee",
    brusnica: "Preiselbeertee",
    frutamali: "Waldfrüchtetee",
    molle: "Apfelsaft",
    pjeshk: "Pfirsichsaft",
    dredhez: "Erdbeersaft",
    vishnje: "Sauerkirschsaft",
    boronic: "Heidelbeersaft",
    portokall: "Orangensaft",
    uj: "Wasser",
    uj_g: "Sprudelwasser",
    makiato_m: "Großer Macchiato",
    makiato_v: "Kleiner Macchiato",
  }
};

document.querySelectorAll('.dropdown-item').forEach(item => {
  item.addEventListener('click', function() {
    const selectedLang = this.dataset.lang;
    
    document.querySelectorAll("[data-i18n]").forEach(el => {
      const key = el.getAttribute("data-i18n");
      if (translations[selectedLang][key]) {
        el.textContent = translations[selectedLang][key];
      }
    });
  });
});
